/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.vo.lowcost.type;

import java.util.ArrayList;
import nc.vo.pub.*;
/**
 * 此处插入类型说明。
 * 
 * 创建日期：(2005-9-16)
 * @author：
 */
public class TypeVO extends CircularlyAccessibleValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = -620715137581358575L;
	public String m_pk_lctype;
	public String m_pk_parent;
	public String m_lctypecode;
	public String m_lctypename;
	public String m_def1;
	public String m_def2;
	public String m_def3;
	public String m_def4;
	public String m_def5;

	/**
	 *     描述上面属性的FieldObjects。主要用于系统工具中，
	 * 业务代码中不会用到下面的FieldObjects。
	 */
	private static StringField m_pk_lctypeField;
	private static StringField m_pk_parentField;
	private static StringField m_lctypecodeField;
	private static StringField m_lctypenameField;
	private static StringField m_def1Field;
	private static StringField m_def2Field;
	private static StringField m_def3Field;
	private static StringField m_def4Field;
	private static StringField m_def5Field;
/**
 * 使用主键字段进行初始化的构造子。
 *
 * 创建日期：(2005-9-16)
 */
public TypeVO() {

}
/**
 * 使用主键进行初始化的构造子。
 *
 * 创建日期：(2005-9-16)
 * @param ??fieldNameForMethod?? 主键值
 */
public TypeVO(String newPk_lctype) {

	// 为主键字段赋值:
	m_pk_lctype = newPk_lctype;
}
/**
 * 根类Object的方法,克隆这个VO对象。
 *
 * 创建日期：(2005-9-16)
 */
public Object clone() {

	// 复制基类内容并创建新的VO对象：
	Object o = null;
	try {
		o = super.clone();
	} catch (Exception e) {}
	TypeVO type = (TypeVO)o;

	// 你在下面复制本VO对象的所有属性：

	return type;
}
/**
 * 返回数值对象的显示名称。
 *
 * 创建日期：(2005-9-16)
 * @return java.lang.String 返回数值对象的显示名称。
 */
public String getEntityName() {

	return "Type";
}
/**
 * 返回对象标识，用来唯一定位对象。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getPrimaryKey() {

	return m_pk_lctype;
}
/**
 * 设置对象标识，用来唯一定位对象。
 *
 * 创建日期：(2005-9-16)
 * @param m_pk_lctype String 
 */
public void setPrimaryKey(String newPk_lctype) {

	m_pk_lctype = newPk_lctype;
}
/**
 * 属性m_pk_lctype的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getPk_lctype() {
	return m_pk_lctype;
}
/**
 * 属性m_pk_parent的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getPk_parent() {
	return m_pk_parent;
}
/**
 * 属性m_lctypecode的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getLctypecode() {
	return m_lctypecode;
}
/**
 * 属性m_lctypename的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getLctypename() {
	return m_lctypename;
}
/**
 * 属性m_def1的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getDef1() {
	return m_def1;
}
/**
 * 属性m_def2的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getDef2() {
	return m_def2;
}
/**
 * 属性m_def3的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getDef3() {
	return m_def3;
}
/**
 * 属性m_def4的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getDef4() {
	return m_def4;
}
/**
 * 属性m_def5的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return String
 */
public String getDef5() {
	return m_def5;
}
/**
 * 属性m_pk_lctype的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_pk_lctype String
 */
public void setPk_lctype(String newPk_lctype) {

	m_pk_lctype = newPk_lctype;
}
/**
 * 属性m_pk_parent的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_pk_parent String
 */
public void setPk_parent(String newPk_parent) {

	m_pk_parent = newPk_parent;
}
/**
 * 属性m_lctypecode的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_lctypecode String
 */
public void setLctypecode(String newLctypecode) {

	m_lctypecode = newLctypecode;
}
/**
 * 属性m_lctypename的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_lctypename String
 */
public void setLctypename(String newLctypename) {

	m_lctypename = newLctypename;
}
/**
 * 属性m_def1的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_def1 String
 */
public void setDef1(String newDef1) {

	m_def1 = newDef1;
}
/**
 * 属性m_def2的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_def2 String
 */
public void setDef2(String newDef2) {

	m_def2 = newDef2;
}
/**
 * 属性m_def3的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_def3 String
 */
public void setDef3(String newDef3) {

	m_def3 = newDef3;
}
/**
 * 属性m_def4的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_def4 String
 */
public void setDef4(String newDef4) {

	m_def4 = newDef4;
}
/**
 * 属性m_def5的setter方法。
 *
 * 创建日期：(2005-9-16)
 * @param newM_def5 String
 */
public void setDef5(String newDef5) {

	m_def5 = newDef5;
}
/**
 * 验证对象各属性之间的数据逻辑正确性。
 *
 * 创建日期：(2005-9-16)
 * @exception nc.vo.pub.ValidationException 如果验证失败，抛出
 *     ValidationException，对错误进行解释。
 */
public void validate() throws ValidationException {

	ArrayList errFields = new ArrayList(); // errFields record those null fields that cannot be null.
	// 检查是否为不允许空的字段赋了空值，你可能需要修改下面的提示信息：
	if (m_pk_lctype == null) {
		errFields.add(new String("m_pk_lctype"));
	}
	// construct the exception message:
	StringBuffer message = new StringBuffer();
	message.append("下列字段不能为空：");
	if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append("、");
			message.append(temp[i]);
		}
		// throw the exception:
		throw new NullFieldException(message.toString());
	}
}
/**
 * <p>需要在一个循环中访问的属性的名称数组。
 * <p>
 * 创建日期：(??Date??)
 * @return java.lang.String[]
 */
public java.lang.String[] getAttributeNames() {

	return new String[]{ "pk_parent", "lctypecode", "lctypename", "def1", "def2", "def3", "def4", "def5" };
}
/**
 *  <p>根据一个属性名称字符串该属性的值。
 *  <p>
 * 创建日期：(2005-9-16)
 * @param key java.lang.String
 */
public Object getAttributeValue(String attributeName) {

	if (attributeName.equals("pk_lctype")) {
		return m_pk_lctype;
	}
	else if (attributeName.equals("pk_parent")) {
		return m_pk_parent;
	}
	else if (attributeName.equals("lctypecode")) {
		return m_lctypecode;
	}
	else if (attributeName.equals("lctypename")) {
		return m_lctypename;
	}
	else if (attributeName.equals("def1")) {
		return m_def1;
	}
	else if (attributeName.equals("def2")) {
		return m_def2;
	}
	else if (attributeName.equals("def3")) {
		return m_def3;
	}
	else if (attributeName.equals("def4")) {
		return m_def4;
	}
	else if (attributeName.equals("def5")) {
		return m_def5;
	}
	return null;
}
/**
 *  <p>对参数name对型的属性设置值。
 *  <p>
 * 创建日期：(2005-9-16)
 * @param key java.lang.String
 */
public void setAttributeValue(String name, Object value) {

	try {
		if (name.equals("pk_lctype")) {
			m_pk_lctype = (String) value;
		}
		else if (name.equals("pk_parent")) {
			m_pk_parent = (String) value;
		}
		else if (name.equals("lctypecode")) {
			m_lctypecode = (String) value;
		}
		else if (name.equals("lctypename")) {
			m_lctypename = (String) value;
		}
		else if (name.equals("def1")) {
			m_def1 = (String) value;
		}
		else if (name.equals("def2")) {
			m_def2 = (String) value;
		}
		else if (name.equals("def3")) {
			m_def3 = (String) value;
		}
		else if (name.equals("def4")) {
			m_def4 = (String) value;
		}
		else if (name.equals("def5")) {
			m_def5 = (String) value;
		}
	}
	catch (ClassCastException e) {
		throw new ClassCastException("setAttributeValue方法中为 " + name + " 赋值时类型转换错误！（值：" + value + "）");
	}
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getPk_lctypeField() {

	if(m_pk_lctypeField == null){
		try{
			m_pk_lctypeField = new StringField();
			// 属性的名称
			m_pk_lctypeField.setName("pk_lctype");
			// 属性的描述
			m_pk_lctypeField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_pk_lctypeField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getPk_parentField() {

	if(m_pk_parentField == null){
		try{
			m_pk_parentField = new StringField();
			// 属性的名称
			m_pk_parentField.setName("pk_parent");
			// 属性的描述
			m_pk_parentField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_pk_parentField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getLctypecodeField() {

	if(m_lctypecodeField == null){
		try{
			m_lctypecodeField = new StringField();
			// 属性的名称
			m_lctypecodeField.setName("lctypecode");
			// 属性的描述
			m_lctypecodeField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_lctypecodeField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getLctypenameField() {

	if(m_lctypenameField == null){
		try{
			m_lctypenameField = new StringField();
			// 属性的名称
			m_lctypenameField.setName("lctypename");
			// 属性的描述
			m_lctypenameField.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_lctypenameField;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getDef1Field() {

	if(m_def1Field == null){
		try{
			m_def1Field = new StringField();
			// 属性的名称
			m_def1Field.setName("def1");
			// 属性的描述
			m_def1Field.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_def1Field;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getDef2Field() {

	if(m_def2Field == null){
		try{
			m_def2Field = new StringField();
			// 属性的名称
			m_def2Field.setName("def2");
			// 属性的描述
			m_def2Field.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_def2Field;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getDef3Field() {

	if(m_def3Field == null){
		try{
			m_def3Field = new StringField();
			// 属性的名称
			m_def3Field.setName("def3");
			// 属性的描述
			m_def3Field.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_def3Field;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getDef4Field() {

	if(m_def4Field == null){
		try{
			m_def4Field = new StringField();
			// 属性的名称
			m_def4Field.setName("def4");
			// 属性的描述
			m_def4Field.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_def4Field;
}
/**
 * FieldObject的Getter方法。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject
 */
public static StringField getDef5Field() {

	if(m_def5Field == null){
		try{
			m_def5Field = new StringField();
			// 属性的名称
			m_def5Field.setName("def5");
			// 属性的描述
			m_def5Field.setLabel("null");
			// 请添加对本属性的期它描述：

		}catch(Throwable exception){
			handleException(exception);
		}
	}
	return m_def5Field;
}
/**
 * 返回这个ValueObject类的所有FieldObject对象的集合。
 *
 * 创建日期：(2005-9-16)
 * @return nc.vo.pub.FieldObject[]
 */
public FieldObject[] getFields() {

	FieldObject[] fields = {getPk_lctypeField(), getPk_parentField(), getLctypecodeField(), getLctypenameField(), getDef1Field(), getDef2Field(), getDef3Field(), getDef4Field(), getDef5Field()};

	return fields;
}
    /* （非 Javadoc）
     * @see java.lang.Object#toString()
     */
    public String toString() {
        // TODO 自动生成方法存根
        if(m_lctypecode!=null & m_lctypename!=null){
            return (m_lctypecode + " " + m_lctypename);
        }
        return super.toString();
    }
}