/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.vo.lowcost.trans;

import nc.vo.pub.*;
import nc.vo.pub.pf.IPfBackCheck;
/**
 * Trans的聚合VO类。
 *
 * 创建日期：(2005-9-22)
 * @author：
 */
public class TransVO extends AggregatedValueObject implements IPfBackCheck {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4045178755307918340L;
	private TransHeaderVO header = null;
	private TransItemVO[] items = null;

	// 时间戳标示，现在暂未使用：
	long currentTimestamp; // 当前时间戳
	long initialTimestamp; // 从数据库读入时获得的时间戳
/**
 * TransVO 构造子注解。
 */
public TransVO() {
	super();
}
/**
 * <p>获得子表的VO数组。
 * <p>
 * 创建日期：(2005-9-22)
 * @return nc.vo.pub.CircularlyAccessibleValueObject[]
 */
public CircularlyAccessibleValueObject[] getChildrenVO() {

	return items;
}
/**
 * <p>获得母表的VO。
 * <p>
 * 创建日期：(2005-9-22)
 * @return nc.vo.pub.CircularlyAccessibleValueObject
 */
public CircularlyAccessibleValueObject getParentVO() {

	return header;
}
/**
 * <p>设置子表的VO数组。
 * <p>
 * 创建日期：(2005-9-22)
 * @param children nc.vo.pub.CircularlyAccessibleValueObject[]
 */
public void setChildrenVO(CircularlyAccessibleValueObject[] children) {

	items = (TransItemVO[]) children;
}
/**
 * <p>设置母表的VO。
 * <p>
 * 创建日期：(2005-9-22)
 * @param parent nc.vo.pub.CircularlyAccessibleValueObject
 */
public void setParentVO(CircularlyAccessibleValueObject parent) {

	header = (TransHeaderVO) parent;
}
/**
 * 为表头VO设置主键，用来唯一定位对象。
 *
 * 创建日期：(2005-9-22)
 * @param pk_trans String 
 */
public void setPrimaryKey(String pk_trans) {

	((TransHeaderVO)getParentVO()).setPrimaryKey(pk_trans);
}
}