/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.bs.lowcost.trans;

import java.rmi.*;
import nc.bs.pub.*;
import nc.vo.lowcost.trans.*;
/**
 * Trans的BO类
 *
 * 创建日期：(2005-9-22)
 * @author：
 */
public class TransBO extends BusinessObject {

/**
	 * 
	 */
	private static final long serialVersionUID = -2219013909740518414L;
/**
 * TransBO 构造子注解。
 */
public TransBO() {
	super();
}
/**
 * EJB规范中要求的方法。
 *
 * 创建日期：(2005-9-22)
 */
public void ejbCreate() {}
/**
 * 通过主键获得VO对象。
 *
 * 创建日期：(2005-9-22)
 * @return nc.vo.lowcost.trans.TransVO
 * @param key String
 * @exception java.rmi.RemoteException 异常说明。
 */
public TransVO findByPrimaryKey(String key) throws java.rmi.RemoteException {

	TransVO trans = null;
	try {
		TransDMO dmo = new TransDMO();
		trans = dmo.findByPrimaryKey(key);
	}
	catch (Exception e) {
		reportException(e);
		throw new RemoteException("TransBean::findByPrimaryKey(TransPK) Exception!", e);
	}
	return trans;
}
/**
 * 向数据库中插入一个VO对象。
 *
 * 创建日期：(2005-9-22)
 * @param trans nc.vo.lowcost.trans.TransVO
 * @return java.lang.String  所插入VO对象的主键字符串。
 * @exception java.rmi.RemoteException 异常说明。
 */
public String insert(TransVO trans) throws RemoteException {

	try {
		TransDMO dmo = new TransDMO();
		String key = dmo.insert(trans);
		return key;
	}
	catch (Exception e) {
		reportException(e);
		throw new RemoteException("TransBO::insert(TransVO) Exception!", e);
	}
}
/**
 * 根据主键在数据库中删除一个VO对象。
 *
 * 创建日期：(2005-9-22)
 * @param key String
 * @exception java.rmi.RemoteException 异常说明。
 */
public void delete(TransVO vo) throws java.rmi.RemoteException {

	try {
		TransDMO dmo = new TransDMO();
		dmo.delete(vo);
	}
	catch (Exception e) {
		reportException(e);
		throw new RemoteException("TransBO::delete(TransPK) Exception!", e);
	}
}
/**
 * 用VO对象的属性值更新数据库。
 *
 * 创建日期：(2005-9-22)
 * @param trans nc.vo.lowcost.trans.TransVO
 * @exception java.rmi.RemoteException 异常说明。
 */
public void update(TransVO trans) throws java.rmi.RemoteException {

	try {
		TransDMO dmo = new TransDMO();
		dmo.update(trans);
	}
	catch (Exception e) {
		reportException(e);
		throw new RemoteException("TransBO::update(TransVO) Exception!", e);
	}
}
}